# Generated by Django 3.2 on 2021-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Producto', models.CharField(max_length=5)),
                ('id_Provedor', models.CharField(max_length=5)),
                ('producto', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('ingresos', models.IntegerField()),
                ('salidas', models.IntegerField()),
                ('saldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Producto', models.CharField(max_length=5)),
                ('id_Provedor', models.CharField(max_length=5)),
                ('producto', models.CharField(max_length=30)),
                ('tamaño', models.IntegerField()),
                ('fecha_de_elaboracion', models.DateField()),
                ('fecha_de_expliracion', models.DateField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Provedor', models.CharField(max_length=5)),
                ('Nombre_provedor', models.CharField(max_length=30)),
                ('dirrecion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('id_Producto', models.CharField(max_length=5)),
            ],
        ),
    ]
