# Generated by Django 3.2 on 2021-04-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='id_Provedor',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id_Provedor',
        ),
    ]
