# Generated by Django 3.2 on 2021-04-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210421_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='saldo',
        ),
        migrations.AlterField(
            model_name='kardex',
            name='id_Producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='producto',
            field=models.CharField(max_length=5),
        ),
    ]
